version: "3"

services:
  django-app:
    build: .
    container_name: todo-django-app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      MONGODB_URI: mongodb://db:27017
      DB_NAME: todo-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    command: >
      sh -c "
        mongod --replSet rs0 --bind_ip_all --logpath /var/log/mongodb.log --logappend &
        sleep 5 &&
        mongosh --eval 'try { rs.initiate({_id:\"rs0\",members:[{_id:0,host:\"localhost:27017\"}]}) } catch(e) { print(e) }' &&
        tail -f /var/log/mongodb.log
      "