version: "3"

services:
  django-app:
    build: .
    container_name: todo-django-app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      MONGODB_URI: mongodb://db:27017/?replicaSet=rs0
      DB_NAME: todo-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./mongo_logs:/var/log/mongodb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand({ping:1})'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
      
    # command to use the mounted log directory
    command: mongod --replSet rs0 --bind_ip_all --logpath /var/log/mongodb/mongodb.log --logappend