version: "3"

services:
  django-app:
    build: .
    container_name: todo-django-app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      MONGODB_URI: mongodb://db:27017
      DB_NAME: todo-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_REPLICA_HOST: ${MONGO_REPLICA_HOST}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand({ping:1})'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

    #to enable replica set, requirement for enabling transactions
    command: >
      sh -c "
        mongod --replSet rs0 --bind_ip_all --logpath /var/log/mongodb.log --logappend &
        sleep 5 &&
        mongosh --eval '
          var config = { _id: \"rs0\", members: [ { _id: 0, host: \"$MONGO_REPLICA_HOST\" } ] };
          try { rs.initiate(config); }
          catch(e) { if (e.codeName === \"AlreadyInitialized\") { print(\"Replica set already initialized.\"); } else { print(\"Error initiating replica set: \" + e); } }' &&
        tail -f /var/log/mongodb.log
      "
