services:
  django-app:
    build: .
    container_name: todo-django-app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      MONGODB_URI: mongodb://db:27017
      DB_NAME: todo-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./scripts/init-replica-set.js:/docker-entrypoint-initdb.d/init-replica-set.js:ro

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ping:1}).ok", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
 
  mongo-express:
    image: mongo-express
    container_name: todo-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - db
