# Generated by Django 5.1.5 on 2025-07-14 13:51

import django.contrib.postgres.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssigneeTaskDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignee_id', models.UUIDField()),
                ('task_id', models.UUIDField()),
                ('relation_type', models.CharField(choices=[('team', 'Team'), ('user', 'User')], max_length=10)),
                ('is_action_taken', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.UUIDField()),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assignee_task_details',
                'indexes': [models.Index(fields=['assignee_id'], name='assignee_ta_assigne_8dbfa4_idx'), models.Index(fields=['task_id'], name='assignee_ta_task_id_28c566_idx'), models.Index(fields=['relation_type'], name='assignee_ta_relatio_4c54c2_idx'), models.Index(fields=['is_active'], name='assignee_ta_is_acti_99caff_idx')],
                'unique_together': {('assignee_id', 'task_id', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'labels',
                'indexes': [models.Index(fields=['name'], name='labels_name_d8f370_idx'), models.Index(fields=['is_deleted'], name='labels_is_dele_5ad206_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('team', 'Team')], default='global', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
                'indexes': [models.Index(fields=['name'], name='roles_name_a96913_idx'), models.Index(fields=['scope'], name='roles_scope_75ec8b_idx'), models.Index(fields=['is_active'], name='roles_is_acti_723ee4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_id', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('deferred', 'Deferred')], default='todo', max_length=20)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deferred_at', models.DateTimeField(blank=True, null=True)),
                ('deferred_till', models.DateTimeField(blank=True, null=True)),
                ('deferred_by', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'indexes': [models.Index(fields=['status'], name='tasks_status_031d4c_idx'), models.Index(fields=['priority'], name='tasks_priorit_a9efa1_idx'), models.Index(fields=['created_by'], name='tasks_created_881111_idx'), models.Index(fields=['created_at'], name='tasks_created_db4e37_idx')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('poc_id', models.UUIDField(blank=True, null=True)),
                ('invite_code', models.CharField(max_length=255, unique=True)),
                ('created_by', models.UUIDField()),
                ('updated_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'teams',
                'indexes': [models.Index(fields=['name'], name='teams_name_12b53a_idx'), models.Index(fields=['invite_code'], name='teams_invite__c2d710_idx'), models.Index(fields=['is_deleted'], name='teams_is_dele_6117d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email_id', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('name', models.CharField(max_length=255)),
                ('picture', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['google_id'], name='users_google__d35fe6_idx'), models.Index(fields=['email_id'], name='users_email_i_bb3678_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTeamDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('team_id', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
                ('role_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField()),
                ('updated_by', models.UUIDField()),
            ],
            options={
                'db_table': 'user_team_details',
                'indexes': [models.Index(fields=['user_id'], name='user_team_d_user_id_34020b_idx'), models.Index(fields=['team_id'], name='user_team_d_team_id_b2c94e_idx'), models.Index(fields=['is_active'], name='user_team_d_is_acti_2eb2ae_idx')],
                'unique_together': {('user_id', 'team_id')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'watchlist',
                'indexes': [models.Index(fields=['task_id'], name='watchlist_task_id_aa6927_idx'), models.Index(fields=['user_id'], name='watchlist_user_id_c64328_idx'), models.Index(fields=['is_active'], name='watchlist_is_acti_8f7f73_idx')],
                'unique_together': {('task_id', 'user_id')},
            },
        ),
    ]
