# Generated by Django 5.1.5 on 2025-08-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial_postgres_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgrestask',
            name='priority',
            field=models.IntegerField(default=3),
        ),
    ]
