# Generated by Django 5.1.5 on 2025-08-22 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial_postgres_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostgresTeamCreationInviteCode",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mongo_id", models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_by", models.CharField(max_length=24)),
                ("used_by", models.CharField(blank=True, max_length=24, null=True)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(auto_now=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[("SYNCED", "Synced"), ("PENDING", "Pending"), ("FAILED", "Failed")],
                        default="SYNCED",
                        max_length=20,
                    ),
                ),
                ("sync_error", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "postgres_team_creation_invite_codes",
            },
        ),
        migrations.RenameIndex(
            model_name="postgresauditlog",
            new_name="postgres_au_mongo_i_e01883_idx",
            old_name="postgres_audit_logs_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresauditlog",
            new_name="postgres_au_action_582248_idx",
            old_name="postgres_audit_logs_action_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresauditlog",
            new_name="postgres_au_collect_4f3415_idx",
            old_name="postgres_audit_logs_collection_name_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresauditlog",
            new_name="postgres_au_documen_2dd530_idx",
            old_name="postgres_audit_logs_document_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresauditlog",
            new_name="postgres_au_user_mo_20b3ab_idx",
            old_name="postgres_audit_logs_user_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresauditlog",
            new_name="postgres_au_timesta_ee4eef_idx",
            old_name="postgres_audit_logs_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresauditlog",
            new_name="postgres_au_sync_st_b7b811_idx",
            old_name="postgres_audit_logs_sync_status_idx",
        ),
        migrations.RenameIndex(
            model_name="postgreslabel",
            new_name="postgres_la_mongo_i_f36969_idx",
            old_name="postgres_labels_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgreslabel",
            new_name="postgres_la_name_25bdde_idx",
            old_name="postgres_labels_name_idx",
        ),
        migrations.RenameIndex(
            model_name="postgreslabel",
            new_name="postgres_la_sync_st_f795eb_idx",
            old_name="postgres_labels_sync_status_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresrole",
            new_name="postgres_ro_mongo_i_018753_idx",
            old_name="postgres_roles_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresrole",
            new_name="postgres_ro_name_ef794d_idx",
            old_name="postgres_roles_name_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresrole",
            new_name="postgres_ro_sync_st_9386cc_idx",
            old_name="postgres_roles_sync_status_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestask",
            new_name="postgres_ta_mongo_i_4bcd8b_idx",
            old_name="postgres_tasks_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestask",
            new_name="postgres_ta_display_0f1eae_idx",
            old_name="postgres_tasks_display_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestask",
            new_name="postgres_ta_status_ae228e_idx",
            old_name="postgres_tasks_status_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestask",
            new_name="postgres_ta_priorit_6ea8ac_idx",
            old_name="postgres_tasks_priority_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestask",
            new_name="postgres_ta_created_a5359a_idx",
            old_name="postgres_tasks_created_by_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestask",
            new_name="postgres_ta_due_at_45ae89_idx",
            old_name="postgres_tasks_due_at_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestask",
            new_name="postgres_ta_sync_st_e67786_idx",
            old_name="postgres_tasks_sync_status_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestaskassignment",
            new_name="postgres_ta_mongo_i_326fa9_idx",
            old_name="postgres_task_assignments_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestaskassignment",
            new_name="postgres_ta_task_mo_95ca3b_idx",
            old_name="postgres_task_assignments_task_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestaskassignment",
            new_name="postgres_ta_user_mo_d13fa3_idx",
            old_name="postgres_task_assignments_user_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestaskassignment",
            new_name="postgres_ta_team_mo_a0605f_idx",
            old_name="postgres_task_assignments_team_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestaskassignment",
            new_name="postgres_ta_status_8b9698_idx",
            old_name="postgres_task_assignments_status_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestaskassignment",
            new_name="postgres_ta_sync_st_385c3f_idx",
            old_name="postgres_task_assignments_sync_status_idx",
        ),
        migrations.RenameIndex(
            model_name="postgrestasklabel",
            new_name="postgres_ta_label_m_8f146d_idx",
            old_name="postgres_task_labels_label_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresteam",
            new_name="postgres_te_mongo_i_abc268_idx",
            old_name="postgres_teams_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresteam",
            new_name="postgres_te_invite__980f9f_idx",
            old_name="postgres_teams_invite_code_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresteam",
            new_name="postgres_te_created_8f28f6_idx",
            old_name="postgres_teams_created_by_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresteam",
            new_name="postgres_te_sync_st_19c6d6_idx",
            old_name="postgres_teams_sync_status_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuser",
            new_name="postgres_us_mongo_i_b7de3d_idx",
            old_name="postgres_users_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuser",
            new_name="postgres_us_google__842c47_idx",
            old_name="postgres_users_google_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuser",
            new_name="postgres_us_email_i_fde0e2_idx",
            old_name="postgres_users_email_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuser",
            new_name="postgres_us_sync_st_4b81bc_idx",
            old_name="postgres_users_sync_status_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuserrole",
            new_name="postgres_us_mongo_i_a0b3f8_idx",
            old_name="postgres_user_roles_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuserrole",
            new_name="postgres_us_user_mo_7d8290_idx",
            old_name="postgres_user_roles_user_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuserrole",
            new_name="postgres_us_role_mo_bbe013_idx",
            old_name="postgres_user_roles_role_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuserrole",
            new_name="postgres_us_team_mo_ffec62_idx",
            old_name="postgres_user_roles_team_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuserrole",
            new_name="postgres_us_sync_st_58315c_idx",
            old_name="postgres_user_roles_sync_status_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuserteamdetails",
            new_name="postgres_us_mongo_i_c533ba_idx",
            old_name="postgres_user_team_details_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuserteamdetails",
            new_name="postgres_us_user_id_50613a_idx",
            old_name="postgres_user_team_details_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuserteamdetails",
            new_name="postgres_us_team_id_468318_idx",
            old_name="postgres_user_team_details_team_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuserteamdetails",
            new_name="postgres_us_is_acti_a58a6c_idx",
            old_name="postgres_user_team_details_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="postgresuserteamdetails",
            new_name="postgres_us_sync_st_bbef4a_idx",
            old_name="postgres_user_team_details_sync_status_idx",
        ),
        migrations.RenameIndex(
            model_name="postgreswatchlist",
            new_name="postgres_wa_mongo_i_06b4ca_idx",
            old_name="postgres_watchlists_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgreswatchlist",
            new_name="postgres_wa_user_mo_e8f264_idx",
            old_name="postgres_watchlists_user_mongo_id_idx",
        ),
        migrations.RenameIndex(
            model_name="postgreswatchlist",
            new_name="postgres_wa_created_2a76a8_idx",
            old_name="postgres_watchlists_created_by_idx",
        ),
        migrations.RenameIndex(
            model_name="postgreswatchlist",
            new_name="postgres_wa_sync_st_19b821_idx",
            old_name="postgres_watchlists_sync_status_idx",
        ),
        migrations.RenameIndex(
            model_name="postgreswatchlisttask",
            new_name="postgres_wa_task_mo_3ecf04_idx",
            old_name="postgres_watchlist_tasks_task_mongo_id_idx",
        ),
        migrations.AlterField(
            model_name="postgresauditlog",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="postgresdeferreddetails",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="postgreslabel",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="postgresrole",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="postgrestask",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="postgrestaskassignment",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="postgrestasklabel",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="postgresteam",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="postgresuser",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="postgresuserrole",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="postgresuserteamdetails",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="postgreswatchlist",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="postgreswatchlisttask",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AddIndex(
            model_name="postgresteamcreationinvitecode",
            index=models.Index(fields=["mongo_id"], name="postgres_te_mongo_i_9b5218_idx"),
        ),
        migrations.AddIndex(
            model_name="postgresteamcreationinvitecode",
            index=models.Index(fields=["code"], name="postgres_te_code_e912c2_idx"),
        ),
        migrations.AddIndex(
            model_name="postgresteamcreationinvitecode",
            index=models.Index(fields=["created_by"], name="postgres_te_created_cc1648_idx"),
        ),
        migrations.AddIndex(
            model_name="postgresteamcreationinvitecode",
            index=models.Index(fields=["is_used"], name="postgres_te_is_used_23eea1_idx"),
        ),
        migrations.AddIndex(
            model_name="postgresteamcreationinvitecode",
            index=models.Index(fields=["sync_status"], name="postgres_te_sync_st_0225fb_idx"),
        ),
    ]
