# Generated by Django 5.1.5 on 2025-01-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostgresRateLimitRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("window_size_minutes", models.IntegerField(default=5)),
                ("num_windows", models.IntegerField(default=3)),
                ("requests_per_second", models.IntegerField(default=120)),
                ("sliding_scale_factor", models.FloatField(default=0.8)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Postgres Rate Limit Rule",
                "verbose_name_plural": "Postgres Rate Limit Rules",
                "db_table": "postgres_rate_limit_rules",
            },
        ),
        migrations.CreateModel(
            name="PostgresRateLimitCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.CharField(db_index=True, max_length=100)),
                ("rule_name", models.CharField(max_length=100)),
                ("window_start", models.DateTimeField()),
                ("request_count", models.IntegerField(default=0)),
                ("last_request_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Postgres Rate Limit Cache",
                "verbose_name_plural": "Postgres Rate Limit Cache",
                "db_table": "postgres_rate_limit_cache",
            },
        ),
        migrations.AddIndex(
            model_name="postgresratelimitcache",
            index=models.Index(
                fields=["identifier", "rule_name", "window_start"], name="postgres_ra_identif_8b2c8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postgresratelimitcache",
            index=models.Index(fields=["created_at"], name="postgres_ra_created_9b2c8c_idx"),
        ),
    ]
