# Generated by Django 5.1.5 on 2025-08-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial_postgres_models'),
    ]

    operations = [
        # Remove the old watchlist tables
        migrations.DeleteModel(
            name='PostgresWatchlistTask',
        ),
        migrations.DeleteModel(
            name='PostgresWatchlist',
        ),
    ]
