# Generated by Django 5.1.5 on 2025-07-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userteamdetails",
            new_name="user_team_d_role_90bebe_idx",
            old_name="user_team_d_role_id_0abcc2_idx",
        ),
        migrations.AlterField(
            model_name="userteamdetails",
            name="role",
            field=models.CharField(max_length=50),
        ),
    ]
