# Generated by Django 5.1.5 on 2025-09-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_postgres_ta_assignee_95ca3b_idx_postgres_ta_assigne_f1c6e7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgresauditlog',
            name='task_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
