# Generated by Django 5.1.5 on 2025-07-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_auditlog_updated_at_auditlog_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assignee",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
