# Generated by Django 5.1.5 on 2025-08-23 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_old_watchlist_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostgresWatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_id', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('task_id', models.CharField(max_length=24)),
                ('user_id', models.CharField(max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=24, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('SYNCED', 'Synced'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='SYNCED', max_length=20)),
                ('sync_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'postgres_watchlist',
                'indexes': [models.Index(fields=['mongo_id'], name='postgres_wa_mongo_i_5c0868_idx'), models.Index(fields=['task_id'], name='postgres_wa_task_id_adb0e4_idx'), models.Index(fields=['user_id'], name='postgres_wa_user_id_71c384_idx'), models.Index(fields=['is_active'], name='postgres_wa_is_acti_ae4d9b_idx'), models.Index(fields=['sync_status'], name='postgres_wa_sync_st_29bd9a_idx'), models.Index(fields=['user_id', 'task_id'], name='postgres_wa_user_id_c1421a_idx')],
                'unique_together': {('user_id', 'task_id')},
            },
        ),
    ]
