# Generated by Django 5.1.5 on 2025-07-24 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_rename_user_team_d_role_id_0abcc2_idx_user_team_d_role_90bebe_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskassignment",
            name="assignee_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tasks_as_user",
                to="todo.user",
            ),
        ),
    ]
