# Generated by Django 5.1.5 on 2025-09-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_rename_postgres_ta_assignee_95ca3b_idx_postgres_ta_assigne_f1c6e7_idx_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postgresuserrole",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="postgresuserrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user_id", "role_name", "scope", "team_id"),
                name="unique_active_user_team_role",
            ),
        ),
    ]
