# Generated by Django 5.1.5 on 2025-09-05 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_postgresauditlog_task_count"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="postgresuserrole",
            unique_together={("user_id", "role_name", "scope", "team_id", "is_active")},
        ),
    ]
