# Generated by Django 5.1.5 on 2025-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_create_new_watchlist_table"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="postgresauditlog",
            name="postgres_au_collect_4f3415_idx",
        ),
        migrations.RemoveIndex(
            model_name="postgresauditlog",
            name="postgres_au_documen_2dd530_idx",
        ),
        migrations.RemoveIndex(
            model_name="postgresauditlog",
            name="postgres_au_user_mo_20b3ab_idx",
        ),
        migrations.RenameField(
            model_name="postgresauditlog",
            old_name="user_mongo_id",
            new_name="assignee_from",
        ),
        migrations.RemoveField(
            model_name="postgresauditlog",
            name="collection_name",
        ),
        migrations.RemoveField(
            model_name="postgresauditlog",
            name="document_id",
        ),
        migrations.RemoveField(
            model_name="postgresauditlog",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="postgresauditlog",
            name="new_values",
        ),
        migrations.RemoveField(
            model_name="postgresauditlog",
            name="old_values",
        ),
        migrations.RemoveField(
            model_name="postgresauditlog",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="postgresauditlog",
            name="assignee_to",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="postgresauditlog",
            name="new_executor_id",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="postgresauditlog",
            name="performed_by",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="postgresauditlog",
            name="previous_executor_id",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="postgresauditlog",
            name="spoc_id",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="postgresauditlog",
            name="status_from",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="postgresauditlog",
            name="status_to",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="postgresauditlog",
            name="task_id",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="postgresauditlog",
            name="team_id",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name="postgresauditlog",
            name="action",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="postgresauditlog",
            index=models.Index(fields=["task_id"], name="postgres_au_task_id_76f799_idx"),
        ),
        migrations.AddIndex(
            model_name="postgresauditlog",
            index=models.Index(fields=["team_id"], name="postgres_au_team_id_aaca90_idx"),
        ),
        migrations.AddIndex(
            model_name="postgresauditlog",
            index=models.Index(fields=["performed_by"], name="postgres_au_perform_f08d1f_idx"),
        ),
    ]
