from enum import Enum


class TaskStatus(Enum):
    TODO = "TODO"
    IN_PROGRESS = "IN_PROGRESS"
    DEFERRED = "DEFERRED"
    BLOCKED = "BLOCKED"
    DONE = "DONE"


class TaskPriority(Enum):
    HIGH = 1
    MEDIUM = 2
    LOW = 3


SORT_FIELD_PRIORITY = "priority"
SORT_FIELD_DUE_AT = "dueAt"
SORT_FIELD_CREATED_AT = "createdAt"
SORT_FIELD_ASSIGNEE = "assignee"

SORT_FIELDS = [
    SORT_FIELD_PRIORITY,
    SORT_FIELD_DUE_AT,
    SORT_FIELD_CREATED_AT,
    SORT_FIELD_ASSIGNEE,
]

SORT_ORDER_ASC = "asc"
SORT_ORDER_DESC = "desc"

SORT_ORDERS = [
    SORT_ORDER_ASC,
    SORT_ORDER_DESC,
]


SORT_FIELD_DEFAULT_ORDERS = {
    SORT_FIELD_CREATED_AT: SORT_ORDER_DESC,
    SORT_FIELD_DUE_AT: SORT_ORDER_ASC,
    SORT_FIELD_PRIORITY: SORT_ORDER_DESC,
    SORT_FIELD_ASSIGNEE: SORT_ORDER_ASC,
}

MINIMUM_DEFERRAL_NOTICE_DAYS = 20
