name: Tests
on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim-bookworm
    services:
      db:
        image: mongo:latest
        ports:
          - 27017:27017
    
    env:
      MONGODB_URI: mongodb://db:27017
      DB_NAME: todo-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.*'

      - name: Install dependencies
        run: |
          python3.11 -m pip install -r requirements.txt

      - name: Lint check
        run: |
          ruff check

      - name: Run tests
        run: |
          python3.11 manage.py test