name: Tests
on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[skip tests]') }}

    env:
      MONGODB_URI: mongodb://db:27017
      DB_NAME: todo-app
      GOOGLE_JWT_ACCESS_LIFETIME: "3600"
      GOOGLE_JWT_REFRESH_LIFETIME: "604800"
      GOOGLE_OAUTH_CLIENT_ID: "test-client-id"
      GOOGLE_OAUTH_CLIENT_SECRET: "test-client-secret"
      COOKIE_SECURE: "False"
      COOKIE_SAMESITE: "Lax"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.*"

      - name: Install dependencies
        run: |
          python3.11 -m pip install -r requirements.txt

      - name: Lint check
        run: |
          ruff check

      - name: Run tests
        run: |
          python3.11 manage.py test
